# Generated by Django 3.2.7 on 2022-10-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MigrationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("bmp", "BMP"),
                            ("cgimage", "CGIMAGE"),
                            ("canon", "CANON"),
                            ("dot", "DOT"),
                            ("gv", "GV"),
                            ("xdot", "XDOT"),
                            ("xdot1.2", "XDOT1.2"),
                            ("xdot1.4", "XDOT1.4"),
                            ("eps", "EPS"),
                            ("exr", "EXR"),
                            ("fig", "FIG"),
                            ("gd", "GD"),
                            ("gd2", "GD2"),
                            ("gif", "GIF"),
                            ("gtk", "GTK"),
                            ("ico", "ICO"),
                            ("cmap", "CMAP"),
                            ("ismap", "ISMAP"),
                            ("imap", "IMAP"),
                            ("cmapx", "CMAPX"),
                            ("imap_np", "IMAP_NP"),
                            ("cmapx_np", "CMAPX_NP"),
                            ("jpg", "JPG"),
                            ("jpeg", "JPEG"),
                            ("jpe", "JPE"),
                            ("jp2", "JP2"),
                            ("json", "JSON"),
                            ("json0", "JSON0"),
                            ("dot_json", "DOT_JSON"),
                            ("xdot_json", "XDOT_JSON"),
                            ("pdf", "PDF"),
                            ("pic", "PIC"),
                            ("pct", "PCT"),
                            ("pict", "PICT"),
                            ("plain", "PLAIN"),
                            ("plain-ext", "PLAIN-EXT"),
                            ("png", "PNG"),
                            ("pov", "POV"),
                            ("ps2", "PS2"),
                            ("psd", "PSD"),
                            ("sgi", "SGI"),
                            ("svg", "SVG"),
                            ("svgz", "SVGZ"),
                            ("tga", "TGA"),
                            ("tif", "TIF"),
                            ("tiff", "TIFF"),
                            ("tk", "TK"),
                            ("vml", "VML"),
                            ("vmlz", "VMLZ"),
                            ("vrml", "VRML"),
                            ("wbmp", "WBMP"),
                            ("webp", "WEBP"),
                            ("xlib", "XLIB"),
                            ("x11", "X11"),
                        ],
                        default="gv",
                        max_length=10,
                        verbose_name="Visualization File Output Format",
                    ),
                ),
                ("graph_source", models.TextField(blank=True, null=True)),
                (
                    "output_file",
                    models.FileField(blank=True, null=True, upload_to="migration_vis/"),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("modified_at", models.DateField(auto_now=True)),
            ],
        ),
    ]
